'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _20131013232328a0dls1vc9h66zvp3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_20131013232328a0dls1vc9h66zvp3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _885216158_preview_59f44cadd087f4c675457d9ae18d90d66d1a08ab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_885216158_preview_59f44cadd087f4c675457d9ae18d90d66d1a08ab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aether_Dragon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aether_Dragon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Akrambuela() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Akrambuela", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alleyn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alleyn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Autumn_Dragon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Autumn_Dragon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property background_music() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("background_music", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blood_knight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blood_knight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonStock1d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonStock1d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttonStock1d_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttonStock1d_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property card_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("card_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property cloth() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("cloth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coollogo_com_9864201() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coollogo_com_9864201", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Curse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Curse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dark_Dragon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dark_Dragon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dark_warden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dark_warden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Darklurker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Darklurker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dead_king_s_ivy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dead_king_s_ivy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property deeproot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deeproot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desature_druid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desature_druid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desature_knight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desature_knight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desature_lord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desature_lord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desature_witch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desature_witch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desmos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desmos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dr__deadlift() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dr__deadlift", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dragon_Commander() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dragon_Commander", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dragon_Dominion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dragon_Dominion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dragon_lord_by_peterprime_d5w0bxu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dragon_lord_by_peterprime_d5w0bxu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property dragon_lord_by_peterprime_d5w0bxu___copy_256px() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("dragon_lord_by_peterprime_d5w0bxu___copy_256px", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dragon_lord_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dragon_lord_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dragon_Paladin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dragon_Paladin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dragon_Warlord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dragon_Warlord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Drakthar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Drakthar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Draw_Cards() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Draw_Cards", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch37\stshfhich37\stshfbi37\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}
        '''{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f10\fbidi \fnil\fchars [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Dreadmare_Instructions() As String
            Get
                Return ResourceManager.GetString("Dreadmare_Instructions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property druidimage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("druidimage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eKE5D8H() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eKE5D8H", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property embody() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("embody", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property End_Turn_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("End_Turn_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property endarken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("endarken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property enforcement() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enforcement", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ennrith() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ennrith", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ennrith_Unleashed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ennrith_Unleashed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ent_archer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ent_archer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ent_shaman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ent_shaman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch31506\stshfhich31506\stshfbi31506\deflang1033\deflangfe1033\themelang2057\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        '''{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f42\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0606030504020204}Open Sans;}{\flomaj [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Epq_References() As String
            Get
                Return ResourceManager.GetString("Epq_References", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equilibrium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equilibrium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property etheral_sacrifice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("etheral_sacrifice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property executioner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("executioner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exitbutton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exitbutton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fairy_Dragon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fairy_Dragon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flying_flag__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flying_flag__1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flying_flag__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flying_flag__2_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flying_flag__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flying_flag__3_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flying_flag__4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flying_flag__4_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fox_archer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fox_archer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property great_ent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("great_ent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Guatzelin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guatzelin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hallowed_Warlord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hallowed_Warlord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hasty_grave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hasty_grave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hell_Drake() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hell_Drake", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jadirrayis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jadirrayis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kingd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kingd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kings_blessing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kings_blessing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kingsroad_ui_elements() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kingsroad_ui_elements", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property last_stand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("last_stand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property last_sun_soldier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("last_sun_soldier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property laurel_crown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("laurel_crown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lizard_rider() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lizard_rider", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mini_credits_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mini_credits_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mini_intructions_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mini_intructions_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mouse_warrior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mouse_warrior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property music_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("music_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nergal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nergal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nergals_secret() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nergals_secret", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property night_rider() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("night_rider", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nullify() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nullify", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nullify_aura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nullify_aura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property overgrowth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("overgrowth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pilgrimage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pilgrimage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Play_Card() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Play_Card", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pointy_sword() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pointy_sword", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pointy_sword__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pointy_sword__2_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property praetorian_tercius_by_peterprime_d5ijpbl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("praetorian_tercius_by_peterprime_d5ijpbl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property recycle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recycle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Red_Tree_Blossom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Red_Tree_Blossom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reinforce() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reinforce", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rejuvinate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rejuvinate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property replenish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("replenish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property revive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("revive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shadow_Drake() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shadow_Drake", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sharped_teeth_skull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sharped_teeth_skull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sharped_teeth_skull__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sharped_teeth_skull__2_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Skeleton_Mage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skeleton_Mage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property spell() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("spell", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spirit_warrior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spirit_warrior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property sword_unsheathe() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sword_unsheathe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tainted_growth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tainted_growth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property the_faceless_druid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("the_faceless_druid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thorkel_Asvard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thorkel_Asvard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tormented_dregs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tormented_dregs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Transform() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Transform", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tuxpi_com_1490732288() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tuxpi_com_1490732288", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tuxpi_com_1490732306() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tuxpi_com_1490732306", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tuxpi_com_1490732416() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tuxpi_com_1490732416", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tuxpi_com_1490732613() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tuxpi_com_1490732613", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Twin_Knights() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Twin_Knights", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property unleash_nergal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unleash_nergal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property unleash_wyvern() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unleash_wyvern", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vs_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vs_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property watcher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("watcher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property witch_character() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("witch_character", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Zyrgym() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zyrgym", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
